# Generated by Django 2.1.7 on 2019-07-30 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0006_auto_20190318_1023'),
        ('assets', '0036_auto_20190716_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=1024)),
                ('job_status', models.BooleanField(choices=[(True, True), (False, False)], default=True)),
                ('build_status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('RUNNING', 'RUNNING'), ('FAILURE', 'FAILURE')], max_length=128)),
                ('log_path', models.CharField(blank=True, max_length=256, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_build_time', models.DateTimeField(null=True)),
                ('published_time', models.DateTimeField(null=True)),
                ('build_console_output', models.TextField(blank=True)),
                ('last_success_build_num', models.IntegerField(null=True)),
                ('last_build_num', models.IntegerField(null=True)),
                ('build_file_path', models.CharField(max_length=1024, null=True)),
                ('deploy_file_path', models.CharField(max_length=1024, null=True)),
                ('dest_file_path', models.CharField(max_length=1024, null=True)),
                ('backup_file_path', models.CharField(max_length=1024, null=True)),
                ('published_status', models.BooleanField(default=True)),
                ('bound_asset', models.ManyToManyField(blank=True, to='assets.Asset', verbose_name='Assets')),
            ],
        ),
        migrations.CreateModel(
            name='DeployRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('deploy_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(default=True)),
                ('record_type', models.CharField(choices=[('DEPLOY', '发布'), ('ROLLBACK', '回滚')], default='DEPLOY', max_length=128)),
                ('app_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deploy.DeployList', verbose_name='App Name')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Asset', verbose_name='Asset Name')),
                ('deploy_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.AdHocRunHistory', verbose_name='History')),
            ],
        ),
        migrations.CreateModel(
            name='DeployVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version_path', models.CharField(max_length=1024, null=True)),
                ('symbol', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_success_build_num', models.IntegerField(null=True)),
                ('version_status', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=1024, null=True)),
                ('backup_file_path', models.CharField(max_length=1024, null=True)),
                ('app_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deploy.DeployList', verbose_name='App Name')),
                ('assets', models.ManyToManyField(blank=True, to='assets.Asset', verbose_name='Assets')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.AddField(
            model_name='deployrecord',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deploy.DeployVersion', verbose_name='App version'),
        ),
        migrations.AddField(
            model_name='deploylist',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Project', verbose_name='项目'),
        ),
    ]
