# Generated by Django 2.1 on 2018-11-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0011_auto_20181119_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylist',
            name='published_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deployversion',
            name='last_success_build_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deployversion',
            name='version_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='symbol',
            field=models.BooleanField(default=True),
        ),
    ]
