# Generated by Django 2.1.7 on 2019-07-30 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DbInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(db_index=True, max_length=32)),
                ('instance_name', models.CharField(db_index=True, max_length=32)),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP')),
                ('port', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='InceptionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('back_host', models.GenericIPAddressField()),
                ('back_port', models.CharField(max_length=32)),
                ('back_user', models.CharField(max_length=32)),
                ('back_password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SqlOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=50)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('sql', models.TextField(verbose_name='SQL语句')),
                ('status', models.SmallIntegerField(choices=[(0, '未审核'), (1, '已驳回'), (2, '未执行'), (3, '执行成功'), (4, '执行失败')], default=0, verbose_name='任务状态')),
                ('type', models.SmallIntegerField(choices=[(0, 'DDL'), (1, 'DML')], verbose_name='语句类型')),
                ('backup', models.SmallIntegerField(choices=[(0, 'not backup'), (1, 'backup')], verbose_name='是否备份')),
                ('text', models.CharField(max_length=100, verbose_name='任务说明')),
                ('exec_time', models.DateTimeField(null=True)),
                ('dbinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbops.DbInfo', verbose_name='数据库')),
                ('exec_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exec_user', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submit_user', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
        ),
        migrations.CreateModel(
            name='SqlRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('sql', models.TextField()),
                ('sequence', models.CharField(max_length=50)),
                ('error', models.TextField(null=True)),
                ('affectrow', models.CharField(max_length=100, null=True)),
                ('execute_time', models.CharField(max_length=150, null=True)),
                ('backup_dbname', models.CharField(max_length=100, null=True)),
                ('sqlsha1', models.TextField(null=True)),
            ],
        ),
    ]
