# Generated by Django 2.1.7 on 2019-08-07 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True)),
                ('sid', models.CharField(max_length=20)),
                ('svn_path', models.CharField(db_index=True, max_length=512)),
                ('sql_file_path', models.CharField(max_length=512)),
                ('sql_file_name', models.CharField(db_index=True, max_length=512)),
                ('work_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sqlorder',
            name='create_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='submit_user',
            field=models.CharField(max_length=64, verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'DDL'), (1, 'DML'), (2, 'GRT'), (3, 'TAB'), (4, 'IND')], verbose_name='语句类型'),
        ),
    ]
