# Generated by Django 2.1 on 2019-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0002_auto_20190527_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dbinfo',
            name='port',
            field=models.CharField(max_length=32),
        ),
    ]
