# Generated by Django 2.1 on 2019-05-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0005_inceptioninfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InceptionInfo',
        ),
    ]
