# Generated by Django 2.1 on 2019-05-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0006_delete_inceptioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InceptionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('back_host', models.GenericIPAddressField()),
                ('back_port', models.CharField(max_length=32)),
                ('back_user', models.CharField(max_length=32)),
                ('back_password', models.CharField(max_length=32)),
            ],
        ),
    ]
