# Generated by Django 2.1 on 2019-05-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0007_inceptioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('insert_date', models.DateTimeField(blank=True)),
                ('sql', models.TextField(blank=True)),
                ('status', models.IntegerField(blank=True)),
                ('type', models.SmallIntegerField(blank=True)),
                ('backup', models.SmallIntegerField(blank=True)),
                ('text', models.CharField(max_length=100)),
                ('dbinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dbops.DbInfo')),
            ],
        ),
    ]
