# Generated by Django 2.1 on 2019-05-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0008_sqlorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlorder',
            name='backup',
            field=models.SmallIntegerField(choices=[(0, 'not backup'), (1, 'backup')]),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='sql',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'DDL'), (1, 'DML')]),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='work_id',
            field=models.CharField(max_length=50),
        ),
    ]
