# Generated by Django 2.1 on 2019-05-31 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0009_auto_20190531_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlorder',
            name='username',
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='dbinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbops.DbInfo'),
        ),
    ]
