# Generated by Django 2.1 on 2019-06-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0011_sqlorder_submit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbinfo',
            name='password',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbinfo',
            name='username',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='backup',
            field=models.SmallIntegerField(choices=[(0, 'not backup'), (1, 'backup')], verbose_name='是否备份'),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='dbinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbops.DbInfo', verbose_name='数据库'),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='sql',
            field=models.TextField(verbose_name='SQL语句'),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='text',
            field=models.CharField(max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'DDL'), (1, 'DML')], verbose_name='语句类型'),
        ),
    ]
