# Generated by Django 2.1 on 2019-06-06 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbops', '0013_auto_20190605_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlorder',
            name='exec_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqlorder',
            name='exec_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exec_user', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='submit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submit_user', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
