# Generated by Django 2.1 on 2019-06-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0014_auto_20190606_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlrecord',
            old_name='workid',
            new_name='work_id',
        ),
    ]
