# Generated by Django 2.1 on 2019-07-30 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbops', '0015_auto_20190614_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlorder',
            name='submit_user',
        ),
        migrations.AddField(
            model_name='sqlorder',
            name='create_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未审核'), (1, '已驳回'), (2, '未执行'), (3, '执行成功'), (4, '执行失败')], default=0, verbose_name='任务状态'),
        ),
    ]
