# Generated by Django 2.1 on 2019-07-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0016_auto_20190730_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlorder',
            name='submit_user',
            field=models.CharField(default=None, max_length=10, verbose_name='提交人'),
            preserve_default=False,
        ),
    ]
