# Generated by Django 2.1 on 2019-07-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0017_sqlorder_submit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(unique=True)),
                ('sid', models.CharField(max_length=20)),
                ('svn_path', models.CharField(db_index=True, max_length=512)),
                ('sql_file_path', models.CharField(max_length=512)),
                ('sql_file_name', models.CharField(db_index=True, max_length=512)),
                ('work_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sqlorder',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'DDL'), (1, 'DML'), (2, 'GRT'), (3, 'TAB'), (4, 'IND')], verbose_name='语句类型'),
        ),
    ]
