# Generated by Django 2.1 on 2019-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbops', '0018_auto_20190731_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqltask',
            name='task_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
